
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Numan
 */
public class bilgigoruntule extends javax.swing.JFrame {

    /**
     * Creates new form bilgigoruntule
     */
    public bilgigoruntule() {
        initComponents();
        
        ogrencininaldigiderslerlistele();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ogrencininaldigiderslertbl = new javax.swing.JTable();
        donemcombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ogrencininaldigiderslertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ogrencininaldigiderslertbl);

        donemcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. DÖNEM", "2. DÖNEM", "3. DÖNEM", "4. DÖNEM", "5. DÖNEM", "6. DÖNEM", "7. DÖNEM", "8. DÖNEM" }));
        donemcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donemcomboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("DÖNEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(donemcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(donemcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donemcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donemcomboActionPerformed
        
        ogrencininaldigiderslerlistele();
        
        
    }//GEN-LAST:event_donemcomboActionPerformed

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String url = "jdbc:postgresql://localhost:5432/derssecim";
    String user ="postgres";
    String pw = "1234";
    
    hocasayfasi hs = new hocasayfasi();
    
    public void ogrencininaldigiderslerlistele() {
    
        try {

                con = DriverManager.getConnection(url,user,pw);
                st= con.createStatement();
                int donem = donemcombo.getSelectedIndex()+1;
                String sql = "SELECT d.derskodu, d.dersad, d.tur, d.akts, a.not FROM dersler d, ogrencininaldigidersler a where d.derskodu = a.derskodu and a.ogrencino ='" + hs.bilgigoruntulemeogrencino + "' and d.donem = '" + donem + "'";
                ResultSet resultSet = st.executeQuery(sql);

                DefaultTableModel tableModel = new DefaultTableModel();
                ogrencininaldigiderslertbl.setModel(tableModel);

                for (int i = 1; i <= resultSet.getMetaData().getColumnCount(); i++) {
                    tableModel.addColumn(resultSet.getMetaData().getColumnName(i));

                }
                while (resultSet.next()) {
                    Object[] row = new Object[resultSet.getMetaData().getColumnCount()];
                    for (int i = 1; i <= resultSet.getMetaData().getColumnCount(); i++) {
                        row[i - 1] = resultSet.getObject(i);
                    }
                    tableModel.addRow(row);

                }

                for (int i = 0; i <= 500; i++) {
                    ogrencininaldigiderslertbl.setRowHeight(i,50);
                }


                ogrencininaldigiderslertbl.getColumnModel().getColumn(0).setPreferredWidth(50);
                ogrencininaldigiderslertbl.getColumnModel().getColumn(1).setPreferredWidth(500);
                ogrencininaldigiderslertbl.getColumnModel().getColumn(2).setPreferredWidth(50);
                ogrencininaldigiderslertbl.getColumnModel().getColumn(3).setPreferredWidth(50);
                ogrencininaldigiderslertbl.getColumnModel().getColumn(4).setPreferredWidth(50);







                Font customFont = new Font("Arial", Font.BOLD, 14);
                ogrencininaldigiderslertbl.setFont(customFont);

                con.close();

            } catch (SQLException ex) {
                Logger.getLogger(ogrencisayfasi.class.getName()).log(Level.SEVERE, null, ex);
            }

    
    
    
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilgigoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilgigoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilgigoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilgigoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilgigoruntule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> donemcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ogrencininaldigiderslertbl;
    // End of variables declaration//GEN-END:variables
}
